#!/bin/bash

default_term="Fall-2018"
class=$1

if [[ $2 != "" ]]; then
  default_term=$2
fi

function create_wk_folders() {
  (
  cd $1;
  i=1;
  while [ $i -lt 13 ]; do
    mkdir "week-$i";
    i=$((i+1))
  done
  )
}

function create_base_folder() {
  cd ~/code/abhijay-berkeley/;
  cd $default_term;
  mkdir $class;
  cd $class;
  git init;
  mkdir homework lab notes projects;
  create_wk_folders "homework"
  create_wk_folders "notes"
  create_wk_folders "lab"
}

create_base_folder
