#!/usr/bin/env bash
#
# Usage: swap <fromScreenIndex> <toScreenIndex>
# Example: swap 1 2
#          swap 2 3

if [[ $# -ne 2 ]]; then
  open "hammerspoon://showDisplays"
  exit 0
fi

from="$1"
to="$2"

# Use macOS "open" command to call Phoenix's custom URL scheme
open "hammerspoon://swap?from=$from&to=$to"
